// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0kPJKSOU4qtXrvddyAZFHeXQY2LMrz_M',
    appId: '1:51746516421:web:e77c88b9d209063446afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    authDomain: 'mile-cab-app.firebaseapp.com',
    storageBucket: 'mile-cab-app.appspot.com',
    measurementId: 'G-763ZNR0FZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYD2kRxQohHb4I5bbLbML3mfOnx1x5II',
    appId: '1:51746516421:android:bae337339349fb1846afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    storageBucket: 'mile-cab-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYuIucLF8TsHUwQ9WjVY9juDmP1AbJsM',
    appId: '1:51746516421:ios:ffd9e871846e1e9d46afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    storageBucket: 'mile-cab-app.appspot.com',
    iosClientId: '51746516421-8q82uj13k3sdig9el479d3jl0rqtudnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwYuIucLF8TsHUwQ9WjVY9juDmP1AbJsM',
    appId: '1:51746516421:ios:d445ea44621e695b46afac',
    messagingSenderId: '51746516421',
    projectId: 'mile-cab-app',
    storageBucket: 'mile-cab-app.appspot.com',
    iosClientId: '51746516421-g6u8hkbd5saptifo2jiqh4j2o6mr114c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutTwo.RunnerTests',
  );
}
